/*!
 * \file      Commissioning.h
 *
 * \brief     End device commissioning parameters
 *
 * \copyright Revised BSD License, see section \ref LICENSE.
 *
 * \code
 *                ______                              _
 *               / _____)             _              | |
 *              ( (____  _____ ____ _| |_ _____  ____| |__
 *               \____ \| ___ |    (_   _) ___ |/ ___)  _ \
 *               _____) ) ____| | | || |_| ____( (___| | | |
 *              (______/|_____)_|_|_| \__)_____)\____)_| |_|
 *              (C)2013-2017 Semtech
 *
 * \endcode
 *
 * \author    Miguel Luis ( Semtech )
 *
 * \author    Gregory Cristian ( Semtech )
 */
#ifndef __LORA_COMMISSIONING_H__
#define __LORA_COMMISSIONING_H__

/*!
 * When set to 1 the application uses the Over-the-Air activation procedure
 * When set to 0 the application uses the Personalization activation procedure
 */
#define OVER_THE_AIR_ACTIVATION                     0

/*!
 * Indicates if the end-device is to be connected to a private or public network
 */
#define LORAWAN_PUBLIC_NETWORK                      false

/*!
 * Mote device IEEE EUI (big endian)
 *
 * \remark In this application the value is automatically generated by calling
 *         BoardGetUniqueId function
 */
#define LORAWAN_DEVICE_EUI                          { 0x10, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01 }

/*!
 * Application IEEE EUI (big endian)
 */
#define LORAWAN_APPLICATION_EUI                     { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 }

/*!
 * AES encryption/decryption cipher application key
 */
#define LORAWAN_APPLICATION_KEY                     { 0x20, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01 }

/*!
 * Current network ID
 */
#define LORAWAN_NETWORK_ID                          ( uint32_t )0


// NWSKey: 8c7dc05ff519285ddd0c1f7dbffea346
// APPKey: 1999accc01a32694ba57810d7ee7fab8
// dvAddr: 2208fe6f

/*!
 * Device address on the network (big endian)
 *
 * \remark In this application the value is automatically generated using
 *         a pseudo random generator seeded with a value derived from
 *         BoardUniqueId value if LORAWAN_DEVICE_ADDRESS is set to 0
 */
// #define LORAWAN_DEVICE_ADDRESS                      ( uint32_t )0x007e6ae1
#define LORAWAN_DEVICE_ADDRESS                      ( uint32_t )0x2208fe6f

/*!
 * AES encryption/decryption cipher network session key
 */
// #define LORAWAN_NWKSKEY                             { 0xd7, 0x2c, 0x78, 0x75, 0x8c, 0xdc, 0xca, 0xbf, 0x55, 0xee, 0x4a, 0x77, 0x8d, 0x16, 0xef, 0x67 }
#define LORAWAN_NWKSKEY                                { 0x8C, 0x7D, 0xC0, 0x5F, 0xF5, 0x19, 0x28, 0x5D, 0xDD, 0x0C, 0x1F, 0x7D, 0xBF, 0xFE, 0xA3, 0x46 }

/*!
 * AES encryption/decryption cipher application session key
 */
// #define LORAWAN_APPSKEY                             { 0x15, 0xb1, 0xd0, 0xef, 0xa4, 0x63, 0xdf, 0xbe, 0x3d, 0x11, 0x18, 0x1e, 0x1e, 0xc7, 0xda, 0x85 }
#define LORAWAN_APPSKEY                                { 0x19, 0x99, 0xAC, 0xCC, 0x01, 0xA3, 0x26, 0x94, 0xBA, 0x57, 0x81, 0x0A, 0x7E, 0xE7, 0xFA, 0xB8 }

#endif // __LORA_COMMISSIONING_H__
